### ISSUE TITLE
Music still plays after logging out

### ISSUE THREAD

**Issue by maxxcrawford** [Poolside-FM/Web#7]
## General Info

+ URL: https://shakira.poolside.fm/ 
+ OS/Browser Version: Firefox 65.0 / OSX 10.12.6 

## Issue Summary

After clicking the "log out" button and being redirected to the ASCII splash screen, the music still plays. 

## Expected Results

Music should stop when a user log outs. 

## Steps to reproduce

1. Login to account (under _Connect to the Pool_) 
2. Click "play" on music window
3. Click "log out"

**Comment by poolsidefm** [comment]
I'd suggest just putting them back to the desktop instead of back to splash screen

**Comment by lewisking** [comment]
@poolsidefm that's the plan, but it's a bit fucked at the moment, haha!

**Comment by lewisking** [comment]
This is now fixed :)
